### ISSUE TITLE
Canvas v5 ellipse broken in Firefox 35.0.1

### ISSUE THREAD

**Issue by tylerault** [google/canvas-5-polyfill#1]
Using the Canvas v5 polyfill in Firefox 35.0.1, the ellipse method is undefined (both on context and the prototype). This was working in Firefox 30, and the same code works in IE10 on the same machine.

Likely up to Mozilla to fix/allow, but posting this here to help others.

Confirmed on multiple PCs. Have not tried other polyfill methods.

Temporary workaround:

``` javascript
// ctx = CanvasRenderingContext2D
drawEllipse: function(ctx, x, y, radiusX, radiusY, rotation, startAngle, endAngle, antiClockwise) {
    ctx.save();
    ctx.translate(x, y);
    ctx.rotate(rotation);
    ctx.scale(radiusX, radiusY);
    ctx.arc(0, 0, 1, startAngle, endAngle, antiClockwise);
    ctx.restore();
}
```

**Comment by tylerault** [comment]
Left a bug report with Mozilla. Confirmed this is failing on Mac OS-X as well.
https://bugzilla.mozilla.org/show_bug.cgi?id=1135244

**Comment by Ms2ger** [comment]
canvasv5.js assumes that the `ellipse` polyfill is only necessary when `Path2D` isn't implemented; this is all yours.

**Comment by jcgregorio** [comment]
Correct, this was an issue with the polyfill that only showed up when Firefox implemented Path2D, which then accidentally hid the ellipse polyfill. I've moved the ellipse polyfill outside of the Path2D polyfill and pushed a 0.1.1 version that should fix the issue.

**Comment by ghost** [comment]
i'd like to pay attention to the <b>performance</b> side of the ellipse function.
i found that the original ctx.ellipse (moreover it doesn't work in Firefox) is quite slow (when rotation angle is non-zero). So i've tried to measure speed of the approximation by bezier curves.
Performance tests (50000 ellipses 100x60 px with rotation angle 0.3 rad):
original ctx.ellipse = 41600 ms
drawEllipse by tylerault = 49900 ms
approx by bezier curves = 45 ms (!!!)
it is not very accurate (you can see a little misplacement of the curves), but it is incredibly fast, so it is a good solution when you need raw speed. Is is approximated by 2 curves. I think, using 4 curves will make it more precise, and enough fast (around 70-80 ms for that test with 50000 ellipses).

here's the code:

<pre>
function ellipse1(ctx, x, y, rx, ry, rot) {
        ry*=4/3;
        var p1_x=x-rx, p1_y=y,
            p2_x=x+rx, p2_y=y,
            cp1_x, cp1_y,
            cp2_x, cp2_y,
            cp3_x, cp3_y,
            cp4_x, cp4_y,
            p1n_x, p1n_y, dx, dy;
        //
        if (rot) {
            //
            p1n_x=rx*Math.cos(rot) + x;
            p1n_y=rx*Math.sin(rot) + y;
            //
            p2_x-=p1n_x-p1_x;
            p2_y-=p1n_y-p1_y;
            //
            p1_x=p1n_x;
            p1_y=p1n_y;
            //
            dx=ry*Math.sin(rot);
            dy=ry*Math.cos(rot);
            //
            cp1_x=p1_x+dx;
            cp1_y=p1_y-dy;
            cp4_x=p1_x-dx;
            cp4_y=p1_y+dy;
            //
            cp2_x=p2_x+dx;
            cp2_y=p2_y-dy;
            cp3_x=p2_x-dx;
            cp3_y=p2_y+dy;
        } else {
            cp1_x=p1_x;
            cp1_y=p1_y-ry;
            cp4_x=p1_x;
            cp4_y=p1_y+ry;
            //
            cp2_x=p2_x;
            cp2_y=p2_y-ry;
            cp3_x=p2_x;
            cp3_y=p2_y+ry;
        }
        //
        ctx.moveTo(p1_x, p1_y);
        ctx.bezierCurveTo(cp1_x, cp1_y, cp2_x, cp2_y, p2_x, p2_y);
        ctx.bezierCurveTo(cp3_x, cp3_y, cp4_x, cp4_y, p1_x, p1_y);
    }
</pre>

in the first version i used objects (var p1={x: ..., y: ...}) but i've found that it make function work slower, so i've decided to use plenty of simple variables :))

**Comment by ghost** [comment]
What is the timeline for taging a Bower release?

@jcgregorio I don't see where a 0.1.1 release might have been pushed.

**Comment by jcgregorio** [comment]
A 0.1.1 tag has been pushed, sorry for the delay.
