### ISSUE TITLE
0.1.2 not released?

### ISSUE THREAD

**Issue by marwahaha** [google/canvas-5-polyfill#10]
Hi,

@jcgregorio I don't see 0.1.2 as an available release!
https://www.npmjs.com/package/canvas-5-polyfill

Could you help with this?

Best,
Kunal

**Comment by marwahaha** [comment]
@jcgregorio or @e98cuenc or who else can I ping?

**Comment by jcgregorio** [comment]
Sorry, was traveling. Fixed.
