### ISSUE TITLE
What's the use of canvasv5.js and svgpath.js

### ISSUE THREAD

**Issue by BenMantalo** [google/canvas-5-polyfill#17]
Hello,
I don't understand the use of the files _canvasv5.js_ and _svgpath.js_ ?
It seems that only canvas.js is used when I install the library...

Any help ?
Thanks,
Best regards.

**Comment by cartant** [comment]
[`rigger`](https://www.npmjs.com/package/rigger) is used to generate `canvas.js` from `canvasv5.js` and `svgpath.js`. Specifically, `svgpath.js` is included at [this location](https://github.com/google/canvas-5-polyfill/blob/master/canvasv5.js#L34-L35) in `canvasv5.js`. `svgpath.js` includes the parser for path strings that can be passed to the `Path2D` constructor.

If you don't use the `Path2D` constructor that accepts strings, you could opt to use `canvasv5.js` - which is somewhat smaller. Whether or not this is what the author intended, I don't know, but it's something I've taken advantage of.

**Comment by jcgregorio** [comment]
Excellent explanation, thanks!
